### ISSUE TITLE
what's the relation of the prev_leaf and leaf?

### ISSUE THREAD

**Issue by huyuguang** [lightning-li/zkSNARK-toy#2]
As I understand, the verifier does not need the prev_leaf? 
It seems that the proof just hides the Merkle path but not pre-image?
Maybe the function of the code is not zero knowledge, but it is a compression of Merkle path?

**Comment by huyuguang** [comment]
And, would you please give some description about the "sha256_padding"? Why should use it? What does it mean?

**Comment by huyuguang** [comment]
I think I know what is sha256_padding. It's sha256 padding.
https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.180-4.pdf section 5.2.

**Comment by lightning-li** [comment]
@huyuguang you're right, but you can replace sha256 to some encrypt algorithm, you can regard pre-leaf as ciphertext, leaf as plaintext. Thus you can prove that you know a valid plaintext and a valid branch to root but not reveal them. or you can convert relations between pre-leaf and leaf, such as pre-leaf = sha256(leaf).

**Comment by lightning-li** [comment]
I will fix it.
