### ISSUE TITLE
你好，想问zk-snarks里的CRS是固定的吗？

### ISSUE THREAD

**Issue by zk616153275** [lightning-li/zkSNARK-toy#4]
一直没想明白这个问题，难道每个交易的涉及到的ABC多项式都是一样的？如果不一样，那按zk-snarks的说法，CRS不就是需要一直在变吗，求大佬解答下

**Comment by lightning-li** [comment]
是的，每个交易的验证规则都是一致的，因此生成的多项式也是一致的，不同的只是多项式的系数，因此CRS 只需初始化一次，后面所有的交易验证都可以使用

**Comment by zk616153275** [comment]
多谢，我开始陷入了一个误区，前几天已经想明白了，哈哈
